---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.9.0

inputs:
- name: deployments-persi
- name: persi-ci
- name: cf-deployment-concourse-tasks

params: {}

run:
  path: persi-ci/efs/task
