---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfpersi/cf-deployment-concourse-tasks-yq
    tag: latest

inputs:
- name: persi-ci
- name: pcf
- name: bbl-state

outputs:
- name: generated-efs-tile-product-config

run:
  path: persi-ci/scripts/ci/generate_efs_tile_product_config

params:
  AWS_ACCESS_KEY_ID: ~
  AWS_SECRET_ACCESS_KEY: ~
  BBL_ENV: ~
