---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.1.0

inputs:
  - name: director-state
  - name: persi-ci

params: {}

run:
  path: persi-ci/scripts/ci/update_cloud_config.sh