---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.19.0

inputs:
  - name: director-state
  - name: persi-ci

params:
  BBL_IAAS: aws
  BBL_AWS_REGION:
  BBL_AWS_ACCESS_KEY_ID:
  BBL_AWS_SECRET_ACCESS_KEY:


run:
  path: persi-ci/scripts/ci/update_cloud_config.sh
